#!/usr/bin/env bash

repo=$1
hash=$2
target=$3

rm -rf ${target}
git clone ${repo} ${target}

cd ${target}
git checkout ${hash}

cp -R ~/credentials/* .

docker-compose build && docker-compose down && docker-compose up -d

